
FROM node:20-alpine

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

ENV MONGO_URI=$MONGO_URI
ENV JWT_SECRET=$JWT_SECRET
ENV PORT=$PORT
ENV S3_URL=$S3_URL
ENV S3_REGION=$S3_REGION
ENV S3_ENDPOINT=$S3_ENDPOINT
ENV S3_ACCESS_KEY=$S3_ACCESS_KEY
ENV S3_SECRET_KEY=$S3_SECRET_KEY
ENV S3_BUCKET_NAME=$S3_BUCKET_NAME

EXPOSE 5000

CMD ["npm", "run", "start"]